import { Check, Sparkles } from "lucide-react";
import type { Bill } from "@/types";

interface BillSummaryProps {
  bill: Bill;
}

export function BillSummary({ bill }: BillSummaryProps) {
  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2">
        <Sparkles className="w-4 h-4 text-gray-400" />
        <h3 className="text-sm font-semibold text-gray-900">
          Plain Language Summary
        </h3>
      </div>

      {/* Gist - Highlighted */}
      <div className="bg-blue-50 border-l-4 border-blue-200 p-4 rounded-r-xl">
        <p className="text-sm text-gray-900 font-medium leading-relaxed">
          {bill.gist}
        </p>
      </div>

      {/* Full Summary */}
      <div className="bg-white border border-gray-100 rounded-xl p-5 space-y-3">
        {bill.aiSummary.split("\n\n").map((paragraph, idx) => (
          <p key={idx} className="text-sm text-gray-700 leading-relaxed">
            {paragraph}
          </p>
        ))}
      </div>

      {/* Key Points */}
      <div className="bg-gray-50 rounded-xl p-5">
        <h4 className="text-sm font-semibold text-gray-900 mb-3">
          Key Points
        </h4>
        <ul className="space-y-2.5">
          {bill.keyPoints.map((point, idx) => (
            <li key={idx} className="flex gap-3">
              <div className="w-5 h-5 rounded-full bg-gray-900 flex items-center justify-center flex-shrink-0 mt-0.5">
                <Check className="w-3 h-3 text-white" strokeWidth={3} />
              </div>
              <span className="text-sm text-gray-700 leading-relaxed">
                {point}
              </span>
            </li>
          ))}
        </ul>
      </div>

      {/* Disclaimer */}
      <p className="text-xs text-gray-400 text-center">
        Summary generated by AI • Always verify with source documents
      </p>
    </div>
  );
}
